<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>openLuo</RootNamespace>
    <AssemblyName>openLuo.Capabilities</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\openLuo.Foundation\openLuo.Foundation.csproj" />
  </ItemGroup>

</Project>
