<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>openLuo</RootNamespace>
    <AssemblyName>openLuo.Capabilities.Llm</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\openLuo.Capabilities\openLuo.Capabilities.csproj" />
    <ProjectReference Include="..\openLuo.Llm\openLuo.Llm.csproj" />
  </ItemGroup>

</Project>
