<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>OpenLuo.Extensions.Party</RootNamespace>
    <AssemblyName>openLuo.Extension.Party</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\openLuo.Abstractions\openLuo.Abstractions.csproj" />
    <ProjectReference Include="..\..\openLuo\openLuo.csproj" />
  </ItemGroup>
</Project>
